# Configuration Split setting menu items definition
config_ignore.settings:
  title: 'Configuration Ignore settings'
  description: 'List Configuration Ignore settings.'
  route_name: config_ignore.settings
  parent: system.admin_config_development
